repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort
- repo: https://github.com/psf/black
      # Replace by any tag/version:
      # https://github.com/psf/black/tags
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0      # pick a git hash / tag to point to
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
# - repo: local
#   hooks:
#   - id: pytest
#     name: Check pytest unit tests pass
#     # entry: poetry run duty test
#     entry: poetry run duty test
#     pass_filenames: false
#     language: system
#     types: [python]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.8.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: .copier-answers.yml
    # based on
    # https://gitlab.com/smop/pre-commit-hooks/-/blob/master/.pre-commit-hooks.yaml
- repo: local
  hooks:
  - id: check-poetry
    name: Poetry check
    description: Validates the structure of the pyproject.toml file
    entry: poetry check
    language: system
    pass_filenames: false
    files: pyproject.toml
